name: PyTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install project dependencies
      run: poetry install

    - name: Set up .env file
      run: cp sample.env .env

    - name: Build and run Docker containers
      run: docker-compose up --build -d

    - name: Run pytest tests
      run: |
        docker-compose exec web poetry run pytest

    - name: Stop Docker containers
      run: docker-compose down